language: python
dist: trusty

python:
  - 3.6
env:
  - SECRET_KEY="asdfghjklqwertyuiop"
virtualenv:
  system_site_package: true
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run manage.py test
after_success:
  - coveralls
notifications:
  on_success: never
  on_failure: always